### ISSUE TITLE
The next generation of ReactFire

### ISSUE THREAD

**Issue by jhuleatt** [FirebaseExtended/reactfire#135]
See the code in [master](https://github.com/FirebaseExtended/reactfire)

## Summary

We're working on a new version of ReactFire that takes advantage of Hooks, Suspense, and Context, and we want to hear your feedback.

## Sample

See a working example [on StackBlitz](https://stackblitz.com/edit/reactfire-sample)

```jsx
function Burrito() {
  // create a ref
  const firebaseApp = useFirebaseApp();
  const burritoRef = firebaseApp
    .firestore()
    .collection('tryreactfire')
    .doc('burrito');

  // subscribe to the doc. just one line!
  // throws a Promise for Suspense to catch,
  // and then streams live updates
  const burritoDoc = useFirestoreDoc(burritoRef);

  // get the value from the doc
  const isYummy = burritoDoc.data().yummy;

  return <p>The burrito is {isYummy ? 'good' : 'bad'}!</p>;
}

function App() {
  return (
    <FirebaseAppProvider firebaseConfig={firebaseConfig} initPerformance>
      <h1>🌯</h1>
      <SuspenseWithPerf
        fallback={<p>loading burrito status...</p>}
        traceId={'load-burrito-status'}
      >
        <Burrito />
      </SuspenseWithPerf>
    </FirebaseAppProvider>
  );
}
```

Samples of ReactFire interacting with more Firebase products can be found [here](https://github.com/FirebaseExtended/reactfire/tree/master/sample-simple/src).

## Motivation

ReactFire was deprecated because it used outdated React APIs (mixins) and was hard to maintain. However, with moderns React APIs, there is an opportunity to create an awesome and easy-to-use library to integrate Firebase with React.

## Design

We've built the new ReactFire on top of [RxFire](https://www.npmjs.com/package/rxfire#what-is-rxfire). RXFire is a tree-shakeable set of functions that return RXJS observables, making it easy to use across Firebase features. Consumers of ReactFire don’t need to worry about RXFire, and won’t notice it when using ReactFire’s main APIs. However, advanced users can use RXJS to, for example, easily write [more powerful Firestore queries](https://www.npmjs.com/package/rxfire#easily-combine-multiple-firebase-data-sources).

ReactFire's hooks, when they’re first called, will throw a Promise that can be caught by Suspense. Once a value is returned from the Firebase backend, the hooks will pass that value on to your component. If you don't want them to throw a Promise, you can provide an initial value.

We've also added components for common use cases, such as <AuthCheck /> to detect if someone is signed in, and <SuspenseWithPerf /> to wrap a suspense component in a Firebase Performance Monitoring trace. If you have an idea for another such reusable component, please open an issue!

In addition, any child of a `<FirebaseAppProvider />` can use `useFirebaseApp()` to get the firebaseApp.

## Try it out

We’ve published an experimental build under [reactfire@next](https://www.npmjs.com/package/reactfire?activeTab=versions). Code and documentation can be found in the master branch of this repo. We want to hear your feedback!

# Roadmap

Reactfire will remain in Alpha until RxFire moves out of Beta, and [Suspense for Data Fetching](https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#react-16x-mid-2019-the-one-with-suspense-for-data-fetching) is finalized.

**Comment by jamesdaniels** [comment]
`2.0.0-rc.0` has been cut to NPM `@latest`

**Comment by RodyGL** [comment]
I get a **TypeError: Cannot read property '_getService' of undefined** on the AuthCheck component with the new release. I'm using react@experimental with concurrent mode enabled. Any suggestion?

**Comment by cereallarceny** [comment]
@jhuleatt @jamesdaniels What's the best way to track your progress on this issue? Likewise, I'd love to know any plans for documentation that you have outlined. I want to start using ReactFire v2, but I feel it's not easy to apply to my specific use-case without reading source code. Is there some Github project or issue board we can follow?

**Comment by jamesdaniels** [comment]
Closing as outdated & moving future conversations like this to discussions. See https://github.com/FirebaseExtended/reactfire/discussions/309
