### ISSUE TITLE
Incorrect type definitions in hooks?

### ISSUE THREAD

**Issue by Raicuparta** [FirebaseExtended/reactfire#140]
Seems like the type definitions for `useFirestoreDoc` and `useFirestoreCollection` are incorrect:

```typescript
export declare function useFirestoreDoc<T = unknown>(ref: firestore.DocumentReference, options?: ReactFireOptions<T>): firestore.DocumentSnapshot | T;
```

[In a union, `unknown` absorbs everything](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#example-3), so if we don't pass a generic type here the return type will always be `unknown`. I tried to find a way to fix this so I could do a PR myself, but I'm afraid my TypeScript knowledge is lacking.

If I understand correctly, what we want here is to make the return type be `firestore.DocumentSnapshot` by default, or `T` if specified. I opened a PR with a way to do this but I'm really not sure if this is how it's supposed to be done.

### Version info

**React:** 16.8.6

**Firebase:** 6.0.4

**ReactFire:** 2.0.0-canary.fc2be5b

**Typescript:** 3.5.3 (on my machine) and 3.3.3 (on CodeSandox) both show the same problem

### Test case
[Test case on Code Sandbox
](https://codesandbox.io/s/reactfire-typescript-wrong-types-4wq4o)

I didn't try to make the project actually run, because the issue is just the type definitions. The issue isn't visible right away, though, because reactfire can't import from `firebase/app` on Code Sandbox for some reason. Follow these steps to see the problem:

### Steps to reproduce

1. Visit https://codesandbox.io/s/reactfire-typescript-wrong-types-4wq4o
2. Open the file `src/withoutOptions.ts`
3. Right-click `useFirestoreDoc` and select "Go To Definition""
4. Check if the `firebase/app` import is failing. If it is, replace with just `firebase`. Don't save the file, but leave it open (important).
5. Go back to `src/withoutOptions.ts` and check the type of `doc` by hovering the mouse over it.

### Expected behavior

The type should be `firestore.DocumentSnapshot` by default

### Actual behavior

The type is `unknown`

**Comment by jhuleatt** [comment]
@Raicuparta thanks for this issue!

@jamesdaniels do you know what we should do here? There are two (or maybe three) ways to call these functions:

1) Just a ref:
```ts
useFirestoreDoc(ref) // returns a firestore.DocumentSnapshot
```

2) With [`ReactFireOptions`](https://github.com/FirebaseExtended/reactfire/blob/06ad68dd5ceebaab02416038242855dbb3ae3001/reactfire/index.ts#L1):
```ts
const options = {
    startWithValue: 10
};

useFirestoreDoc<number>(ref, options); // returns 10 and then a firestore.DocumentSnapshot
```

3) If `ReactFireOptions` gains other fields, this third option may be possible:
```ts
const options = {
    someFieldThatIsNotStartWithValue: true
};

useFirestoreDoc(ref, options); // returns a firestore.DocumentSnapshot
```
----

Maybe we provide multiple definitions like in [this answer](https://stackoverflow.com/a/43543295/4816918)?

```ts
function useFirestoreDoc(ref: firestore.DocumentReference): firestore.DocumentSnapshot;
function useFirestoreDoc<T>(ref: firestore.DocumentReference, ReactFireOptions<T>): T | firestore.DocumentSnapshot
```

**Comment by jhuleatt** [comment]
Another option is that the useFirestoreDoc hook can internally create a stubbed out DocumentSnapshot based off of the provided data. Then the typedef could look like:

```ts
function useFirestoreDoc(ref: firestore.DocumentReference): StubbedFirestoreDocumentSnapshot | firestore.DocumentSnapshot;
```

**Comment by codediodeio** [comment]
Here's another option. 

It does not make much sense to use a generic because `<Collection|Document>Snapshot` does not take a generic to begin with TBH, I'd rather not have a union type and just manually cast the type to the data. 

OR

The hook could return an object with the `QuerySnapshot` in addition to the data cast to the generic type, for example:

```
interface ReactfireCollection<T> {
  snapshot?: firestore.QuerySnapshot,
  data?: T[]
}

// Usage would look like this:

const { snapshot, data } = useFirestoreCollection<Dog>(ref);
const { snapshot: catSnap, data: catData, } = useFirestoreCollection<Cat>(ref);
```
Benefits: 

1. Eliminates the need for the extra `data` hooks. 
2. Easy to strongly type. Data would take initialValue, so you don't need union types at all.

**Comment by davepwsmith** [comment]
Hi @jhuleatt - I'm looking for easy ways to help out with this (because I'm no expert!), and thought this might be one. Some of the typing looks complicated, but is there a reason that the SDK calls return "any" rather than Promise<firestore.storage.Storage> for example? 

I would also be happy to go ahead and try to get your suggestion above working ("Maybe we provide multiple definitions") - assuming that you haven't decided to change the API and go with @codediodeio's suggestion?

**Comment by jhuleatt** [comment]
@jamesdaniels has redone ReactFire's type handling in a way that should address this. James, think we're ready to close this issue?

**Comment by davepwsmith** [comment]
Works well now for me.

**Comment by jamesdaniels** [comment]
Yeah, I’m calling this one good. Open a new issue for any type problems you experience as of the latest RCs.
