### ISSUE TITLE
FR: Implement a <StorageImage /> component

### ISSUE THREAD

**Issue by jhuleatt** [FirebaseExtended/reactfire#144]
A common Firebase pattern is to save a storage path in Firestore or the Realtime Database, and then use that to get a download URL from Cloud Storage. This is currently doable with useStorageDownloadURL like so:

```jsx
function MyComponent({path, alt}) {
  const imageURL = useStorageDownloadURL(firebaseApp.storage().ref(path));
  return (
    <img src={imageURL} alt={alt} />
  );
}
```

It would probably be helpful to just provide a component that does this for us:

```jsx
<StorageImage path="my/storage/path.jpg" alt="Yummy pasta" />
```

**Comment by samtstern** [comment]
Nice!  This will be a parallel to what FirebaseUI does for Android and
iOS.  Example:
https://firebaseopensource.com/projects/firebase/firebaseui-android/storage/readme.md/
