### ISSUE TITLE
published package is missing commonjs code

### ISSUE THREAD

**Issue by whollacsek** [FirebaseExtended/reactfire#146]
### Version info

**ReactFire:** 2.0.0

**Other (e.g. Node, browser, operating system) (if applicable):**
"next": "9.0.5",
"typescript": "^3.5.3"

### Test case

I just started a new project with next.js and stumbled on this new version of reactfire, I was excited to give it a try but was immediately disappointed by:
```
/home/[REDACTED]/node_modules/reactfire/index.js:1
export * from './auth';
^^^^^^

SyntaxError: Unexpected token export
```

So I opened the reactfire package and found that it doesn't contain commonjs version of source code.

### Steps to reproduce

- create a next.js based project with typescript support
- add reactfire and import it in index.tsx

### Expected behavior

Package published on npm should contain valid/runnable node.js code.

**Comment by jhuleatt** [comment]
@jamesdaniels our current tsconfig outputs `esnext`: https://github.com/FirebaseExtended/reactfire/blob/803159c62ad2f29d1bcddbc76e85f32093889e41/reactfire/tsconfig.json#L4

Is fixing this as simple as changing the config to `UMD`?

**Comment by jamesdaniels** [comment]
@jhuleatt we'll want to build for more than one target before publish. I'll build that into the pipeline.

**Comment by shawnmmatthews** [comment]
Is this issue specific to projects using Typescript or any SSR setup? I'm running a very standard JS based NextJS site and just attempted to add FirebaseAppProvider, and I immediately receive the token error. I see that @jamesdaniels is working on solution in the pipeline. Is there a current work around in the meantime? Thanks again for the awesome project.

**Comment by peterdeepsix** [comment]
I would be willing to put in sometime for PR regarding this issue. @jamesdaniels Let me know if you need any help

**Comment by shawnmmatthews** [comment]
Just as a heads up for anyone that comes across this prior to the update being available. I've been able to get this working by building reactfire using "module": "commonjs" in the tsconfig.json file, and then running the context provider from within a module with ssr: false enabled in Next.
