### ISSUE TITLE
useObservable swallows errors

### ISSUE THREAD

**Issue by ducret201** [FirebaseExtended/reactfire#147]
Hello.

I am using reactfire v2.
I would expect the useObservable to propagate errors which is not the case.
Below is a snippet which demonstrates the issue .

```
    try {
        useObservable(throwError(new Error('error')))
    } catch (error) {
        if (error instanceof Promise) throw error
        console.log('error catched') // this is never called
    }
```

looking at the code, `request.error` is never set.
Let me know if more detail is needed to adresse this issue.

Thanks!

**Comment by jhuleatt** [comment]
Thanks @ducret201! I think this is indeed a quick fix. Can you please give my PR #171 a review?
