### ISSUE TITLE
The simple-sample project does not work

### ISSUE THREAD

**Issue by ryanwarsaw** [FirebaseExtended/reactfire#148]
I was getting errors when I was developing locally about traces, so I figured I'd pull down the demo and take a look and I'm getting a similar result:

> Trace storage-root is started before.

This happens right after you go through the authentication scheme.

**Comment by jhuleatt** [comment]
Thanks for calling this out @ryanwarsaw! I've submitted a fix.

**Comment by ryanwarsaw** [comment]
Thanks for the quick fix, I’ve really enjoyed using this library - do you guys have a todo list somewhere for those interested in contributing?

**Comment by jhuleatt** [comment]
Glad to hear you like it, and I'm excited to hear that you're interested in contributing! I just went through some issues and added 'Help Wanted' tags to things that I think would be good candidates for PRs. Feel free to claim any of those!

Outside of that, if there is anything you'd like to see added to the library (or changed), please open a feature request and we'll discuss it! Or, if you'd just like to play around with the library a bit more, you can post examples of cool things you've made with ReactFire in #160.
