### ISSUE TITLE
requiredClaims for <AuthCheck> is not working. 

### ISSUE THREAD

**Issue by catrawalkar** [FirebaseExtended/reactfire#161]
### Version info

**React:** 16.9.0

**Firebase:** 7.2.0

**ReactFire:** 2.0.0-canary.803159c

**Other (e.g. Node, browser, operating system) (if applicable):**

### Test case

      <AuthCheck fallback={<Login />} requiredClaims={{ismoderator: true}}>
             <span>hello</span>
      </AuthCheck>

Am I doing anything wrong here?? Please suggest..!

### Expected behavior
It should check if user is having requiredclaims.

### Actual behavior

Throws error with undefined things.

**Comment by catrawalkar** [comment]
@jhuleatt  in the code, I can see a comment:

// TODO(jeff) see if this actually works

Can you check please? Is there anything I can do to help here (I am noob). I can try to solve the bug, I dont know TS :(

**Comment by catrawalkar** [comment]
https://github.com/FirebaseExtended/reactfire/blob/803159c62ad2f29d1bcddbc76e85f32093889e41/reactfire/auth/index.tsx#L63

You might be able to resolve just by looking here..


I did this: 


`//Check if user is available`
`if (requiredClaims && user) {`
`        //removed *throw* from below line..`
`        user.getIdTokenResult().then(function(idTokenResult) {`

And this works fine for me now.

**Comment by jhuleatt** [comment]
Hey @catrawalkar, you aren't doing anything wrong, you just caught an old todo that I forgot about 😬. Can you please edit your original post with the actual error message you got? It would help me look into this.

**Comment by jhuleatt** [comment]
I've figured out the problem and created a PR that solves it. If you want to try it out before it gets merged, pull the branch [jh-auth-claims](https://github.com/FirebaseExtended/reactfire/tree/jh-auth-claims) and follow the ["for development" steps](https://github.com/FirebaseExtended/reactfire/tree/jh-auth-claims#for-development)

**Comment by catrawalkar** [comment]
Hello, I followed  "for development" steps,

Following things happened, I am getting following issues:

1. In simple-sample, Firestore.js says it cannot find useFirestoreCollectionData and useFirestoreDocData both the modules.
2. I only had to test Auth module so I commented 1st issue. Now when I write console.log in reactfire source code, I cannot see those console.log in browser. Am I doing anything wrong? Help appreciated.

I would love to help contributing to this library! <3

**Comment by catrawalkar** [comment]
Thank you for quick response. This works as expected.

**Comment by catrawalkar** [comment]
@jhuleatt  Can you merge this asap please?

**Comment by jhuleatt** [comment]
Hi @catrawalkar, I should be able to get a review from another maintainer of this repo today, so I'm hoping to merge this by the end of the day.

**Comment by jhuleatt** [comment]
this might take another day to get a review.

**Comment by catrawalkar** [comment]
@jhuleatt  Is there anything I can do to help you here?

**Comment by wortkotze** [comment]
Hi, I still have the issue in "reactfire": "^2.0.0-alpha.2"
install via @next

when i do an auth check against a claim that is not present at the user its crashing.

`index.js:24 Uncaught C {a: 0, i: undefined, c: C, b: null, f: null, …}
(anonymous) @ index.js:24
commitHookEffectList @ react-dom.development.js:17283
commitLifeCycles @ react-dom.development.js:17316
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
retryTimedOutBoundary @ react-dom.development.js:19789
wrapped @ scheduler-tracing.development.js:207
Promise.then (async)
(anonymous) @ react-dom.development.js:18027
commitWork @ react-dom.development.js:18019
commitAllHostEffects @ react-dom.development.js:18680
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18913
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
render @ react-dom.development.js:21155
./src/index.js @ index.js:5
__webpack_require__ @ bootstrap:785
fn @ bootstrap:150
1 @ Home.js:34
__webpack_require__ @ bootstrap:785
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1 The above error occurred in the <AuthCheck> component:
    in AuthCheck (at Home.js:24)
    in div (at Home.js:23)
    in div (at Home.js:18)
    in Home (created by Context.Consumer)
    in Route (at App.js:9)
    in Switch (at App.js:8)
    in App (at Root.js:14)
    in Suspense (created by SuspenseWithPerf)
    in SuspenseWithPerf (at Root.js:13)
    in ErrorBoundary (at Root.js:12)
    in Router (created by BrowserRouter)
    in BrowserRouter (at Root.js:11)
    in FirebaseAppProvider (at Root.js:10)
    in Root (at src/index.js:5)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
console.<computed> @ index.js:1
r @ backend.js:6
logCapturedError @ react-dom.development.js:17117
logError @ react-dom.development.js:17153
callback @ react-dom.development.js:18094
callCallback @ react-dom.development.js:16433
commitUpdateEffects @ react-dom.development.js:16472
commitUpdateQueue @ react-dom.development.js:16460
commitLifeCycles @ react-dom.development.js:17364
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
retryTimedOutBoundary @ react-dom.development.js:19789
wrapped @ scheduler-tracing.development.js:207
Promise.then (async)
(anonymous) @ react-dom.development.js:18027
commitWork @ react-dom.development.js:18019
commitAllHostEffects @ react-dom.development.js:18680
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18913
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
render @ react-dom.development.js:21155
./src/index.js @ index.js:5
__webpack_require__ @ bootstrap:785
fn @ bootstrap:150
1 @ Home.js:34
__webpack_require__ @ bootstrap:785
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:36 Uncaught Error: Mismatched Claims: {"isAdmin":{"expected":true}}
    at index.js:36
    at e.g (promise.js:832)
    at Kb (promise.js:1170)
    at Gb (promise.js:1141)
    at C.push../node_modules/@firebase/auth/dist/auth.esm.js.k.Xb (promise.js:1112)
    at pb (run.js:132)`


the second thing would be, i have claims that are again an object like: roles:{admin: true, user: false, ...}
would it be possible to integrate this also?

thx Stephan
