### ISSUE TITLE
[Question] SyntaxError: Unexpected token export 

### ISSUE THREAD

**Issue by MuratDoner** [FirebaseExtended/reactfire#163]
Hello,
 (As I do not know if you use Stackoverflow actively, I ask the question here. But we can migrate the question anywhere else, if needed.)

 I used the same steps for sample-simple to run sample-context and I got this error:

```
/Users/murat.doner/IdeaProjects/reactfire/reactfire/pub/reactfire/index.js:1
export * from './auth';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
```
   

As far as I understand, it is something about Babel and Node; but as I am not well-informed about these technologies currently.

**Comment by jhuleatt** [comment]
Hello again @MuratDoner, this is the right spot for these kinds of questions 👍 

I'd suggest sticking to sample-simple for now. I wrote sample-complex a while ago to explore what server rendering might look like for ReactFire, but this is likely to change a lot once [Suspense for server rendering](https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#suspense-for-server-rendering) becomes available. Maybe it is time to get rid of sample-complex until we're more confident in the right server rendering patterns.

**Comment by dannytatom** [comment]
I'm getting this problem just using the simple-example.

```tsx
import React from 'react'
import App from 'next/app'
import { ThemeProvider, CSSReset, ColorModeProvider } from "@chakra-ui/core";
import { FirebaseAppProvider } from 'reactfire';
import 'firebase/performance';
import 'firebase/firestore';

import THEME from '../theme'

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  databaseURL: process.env.FIREBASE_DATABASE_URL,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
  measurementId: process.env.FIREBASE_MEASUREMENT_ID
};

class AvoUp extends App {
  render() {
    const { Component, pageProps } = this.props

    return (
      <FirebaseAppProvider firebaseConfig={firebaseConfig} initPerformance>
        <ThemeProvider theme={THEME}>
          <ColorModeProvider>
            <CSSReset />
          
            <Component {...pageProps} />
          </ColorModeProvider>
        </ThemeProvider>
      </FirebaseAppProvider>
    )
  }
}

export default AvoUp
```

> I wrote sample-complex a while ago to explore what server rendering might look like for ReactFire, but this is likely to change a lot once Suspense for server rendering becomes available.

Unrelated, but does that mean reactfire/suspense doesn't work with SSR/Next.js?

**Comment by dannytatom** [comment]
I'm also getting this error with next.js & typescript. All I've got is:

```typescript
import React from "react";
import App from "next/app";
import Head from "next/head";
import { ThemeProvider, CSSReset, ColorModeProvider } from "@chakra-ui/core";
import { FirebaseAppProvider } from "reactfire";
import "firebase/performance";

import THEME from "../theme";
import FIREBASE_CONFIG from "../firebase.config";

export default class AvoUp extends App {
  render() {
    const { Component, pageProps } = this.props;

    return (
      <FirebaseAppProvider firebaseConfig={FIREBASE_CONFIG} initPerformance>
        <ThemeProvider theme={THEME}>
          <ColorModeProvider>
            <Head>
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <CSSReset />

            <Component {...pageProps} />
          </ColorModeProvider>
        </ThemeProvider>
      </FirebaseAppProvider>
    );
  }
}
```

It could be my tsconfig, but I can't really change any of that cause Next.js just overwrites it next time it runs.

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "strict": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ]
}
```

`.nvmrc` is set to `8.16.2` since running this in a firebase function. Not sure if that matters, just tryna give all the info I can think of lol.

**Comment by dannytatom** [comment]
Ok, yeah, issue is that reactfire's tsconfig uses `module: esnext`. I don't really know if that's something I can fix on my end or if reactfire needs to have it set to `commonjs`. Node 8 doesn't support imports like that, and 8 is required for Firebase Functions. Given this is a firebase library, seems like it should use `commonjs` so that people can use SSR or w/e else via functions while also using this library?

**Comment by dannytatom** [comment]
Turns out this is already being talked about in #146, derp.
