### ISSUE TITLE
limited ability to reactively update Firestore references/data

### ISSUE THREAD

**Issue by cdock1029** [FirebaseExtended/reactfire#166]
### Version info

**React:** `16.10.2`

**Firebase:** `7.2.0`

**ReactFire:** `2.0.0-canary.803159c`

### Feature request

One of the beauties of hooks is provides concise way to "declaratively" specify how a value is calculated and when to run the recalculation given a list of dependencies.

I think the Firestore hooks could use this built in ability to recalculate their references based on provided dependency lists. At the very least the current method of updating the data based on ref path could be improved.

When using pagination to update `startAfter` for example, or flipping `orderBy` direction for sorting, or changing page size `limit`.  Or just changing the id of a `doc` when also using these other query components.. since once it's a query there is no discrimination based on `path` alone which right now is how ref updates can be triggered.

This only seems to be useful when referencing absolute collection paths. Perhaps we could switch this way of identifying a reference to something like

~~JSON.stringify(ref._query)~~
~~ref._query.toString()~~
**edit**:
```js
ref._query.canonicalId()
// https://github.com/firebase/firebase-js-sdk/blob/4ecd58ece02e08132b80ae5e50cfcd831efee762/packages/firestore/src/core/query.ts#L221
//(not sure why this method isn't public on the ref,
//seems very useful to be have a string representation of a query)
// that isn't [object Object]

```

which would allow the id of the ref to incorporate all of its query components.

A limitation of even this improvement is that only strict changes to the reference itself will refetch the data. Other non-query changes to state wouldn't, like toggling some UI data that doesn't strictly map to a path/query change.

In this case, you could have the ref be a function, allow dependency list of when to rerun this function which would return a ref:

```typescript
function useCollection(
  queryBuilder: () => firebase.firestore.Query | undefined,
  deps: any[] = [],
  // other opetional paramters
  // { get } = { get: false },
) {
  // pass that deps list to the deps parameter of some useEffect in here where a firestore 
  // subscription is created. Maybe not possible with current usage of useObservable
}
```
Allowing function to return undefined is useful because you do not always start out with everything you need to build the query (user provided ID, etc) so in that case the returned data should be undefined as well... and won't be rendered.

Usage:

```js
const page = useCollection(() => {
  let ref = undefined
  if (selectedId && !hidden) {
    ref = fs.collection('parentCollection').doc(selectedId).collection('items')
      .orderBy('name', direction).limit(pageSize)
    if (startAfter) {
      ref = ref.startAfter(startAfter)
    }
  }
  return ref  
}, [selectedId, pageSize, startAfter, direction, hidden])
```

This leads to another thought, (I think personal preference), but there doesn't seem much use for observables if you go all in on hooks no? `useObservable` itself kinda seems out of place in this library, as observables aren't really used anywhere else.. and then the library could be smaller if they weren't a part of this. As it stands now there doesn't seem to be a connection of leveraging the power of observable transformations, and the firebase hooks as written.

Here's a bare bones library I made for myself (not maintained really) that played around with these ideas:

https://github.com/cdock1029/fire-hooks/blob/a935842cd9af22548668d3da36fa576584e29a34/src/index.ts#L9

**Comment by jhuleatt** [comment]
cc @davideast 

@cdock1029 good point about the current implementation failing to re-query if the query changes without the path changing, and nice find with `ref._query.canonicalId()`! Unfortunately, it doesn't look like there is an equivalent for Realtime Database. I tried [`toJSON`](https://firebase.google.com/docs/reference/js/firebase.database.Query#tojson) but it didn't return any info about the query besides the path. 

Your suggestion of using a function sounds like a great idea to solve this for both databases. There is another benefit, too. It means that the current pattern of needing to use `useFirebaseApp` to get the Firebase instance to create the ref/query could go away if the hook just supplies the `firebase.firestore()`/`firebase.database()` object to the function.

I think I disagree about returning `undefined` though. If a query isn't ready to be created, I imagine you'd handle that higher up in the component tree and render some placeholder instead. What do you think?

-------

_Regarding the comment about observables, we did that mostly for maintainability. ReactFire is built on top of [RxFire](https://firebaseopensource.com/projects/firebase/firebase-js-sdk/packages/rxfire/readme.md/), and using the RxFire observables with `useObservable` made most of the hooks really simple to implement. If you have strong concerns, please open another issue, but let's keep this thread focused on the database reference ID stuff._

**Comment by cdock1029** [comment]
Great idea with passing the firebase instance to the function. Nice to have all the setup code and dependencies located within the callback.

>I think I disagree about returning undefined though. If a query isn't ready to be created

There was some [discussion about this here](https://github.com/CSFrequency/react-firebase-hooks/pull/10), and [also here along with other discussion](https://github.com/CSFrequency/react-firebase-hooks/issues/5#issuecomment-493470899), in another library that did some nice work integrating firebase and hooks. Maybe worth looking over why the conclusion arrived at allowing `undefined`. I agree not doing so is simpler in one sense, but I think it had to do with hooks not allowing execution inside of `if` statements.

Not always easy to isolate all pieces of UI based on individual parts of state. So you can render, and setup your hook. Then when, say a user selected an item, this runs data fetching but rest of component is ready to go. Otherwise whatever hook was "incomplete" needs to be extracted to its own component, removing the value of hooks consolidation of state logic.

**Comment by jhuleatt** [comment]
@cdock1029 Let's keep the `undefined` conversation going in #178. I'm going to close this issue since we've addressed the ID bug
