### ISSUE TITLE
Can't call useFirestoreDoc or useFirestoreCollection with null query

### ISSUE THREAD

**Issue by mlipscombe** [FirebaseExtended/reactfire#178]
The PR merged in FirebaseExtended/reactfire#167 broke the ability to call `useFirestoreDoc` and `useFirestoreCollection` with a null query.  This is useful to accommodate where dependencies hadn't been calculated yet.

For example:

```
const user = useUser();
const doc = useFirestoreDoc(
  user ? firebase.firestore().collection('x').doc(user.uid) : null
);
```

**Comment by jhuleatt** [comment]
@mlipscombe thanks for the issue!

Can you please clarify what you mean by dependencies that haven't been calculated yet?

We [recommend](https://github.com/FirebaseExtended/reactfire/blob/master/docs/use.md#decide-what-to-render-based-on-a-users-auth-state) gating authentication-related things with the `AuthCheck` component. With that, you can be confident that a user will exist if it renders its children. If your example were the child of an `AuthCheck` component, you could be confident that useUser would always return a user.

```tsx
function UserData() {
  // this throws a Promise until it is ready
  // since this component is a child of AuthCheck,
  // we will always get a User.
  const user = useUser();

  const documentSnap = useFirebaseApp()
    .firestore()
    .collection("x")
    .doc(user.uid);

  // ...
}

function App() {
  return (
    <>
      <h1>Welcome to my app!</h1>
      <h2>Here is your data:</h2>
      <Suspense fallback={"loading..."}>
        <AuthCheck fallback={<SignInPrompt />}>
          <UserData />
        </AuthCheck>
      </Suspense>
    </>
  );
}

```

**Comment by mlipscombe** [comment]
Sorry, I think I explained it rather poorly.  Up until this change, it was possible to have a hook that conditionally performed a query.   It allowed, for example:

```
function UserData() {
  const [enabled, setEnabled] = useState(false);
  const documentSnap = useFirebaseApp()
    .firestore()
    .collection('x')
    .doc('abcd');
  const doc = useFirestoreDoc(enabled ? documentSnap : null);
}
```

Given that you can't change hook order, this is pretty useful.  For comparison, [CSFrequency/react-firebase-hooks](https://github.com/CSFrequency/react-firebase-hooks) supports this.

**Comment by jhuleatt** [comment]
Sorry for the pushback on this. For most cases, it feels like calling `useFirestoreDoc(null)` is a mistake, and I want to treat it as such. If we don't, people's apps might fail in ways they don't expect. For example, doing the check `if (doc.exists === true)` after `useFirestoreDoc` is always safe to do right now. But if we allow `useFirestoreDoc` to take an `undefined` reference, and presumably return `null`, that check will now fail with the error `Cannot read property 'exists' of null`.

Additionally, this change would be a way to get around calling hooks conditionally, but to me it still seems more complicated than breaking out into a new component. 

If we support `null` as an argument:

```jsx
function Sample() {
  const [enabled, setEnabled] = useState(false);
  const documentReference = useFirebaseApp()
    .firestore()
    .collection("x")
    .doc("abcd");
  const doc = useFirestoreDoc(enabled ? documentReference : null);

  if (!enabled) {
    return <Placeholder />;
  } else {
    return <p>{doc.data().x}</p>;
  }
}
```

If we broke things out into another component, it is (IMO) easier to understand:

```jsx
function Data() {
  const documentReference = useFirebaseApp()
    .firestore()
    .collection("x")
    .doc("abcd");
  const doc = useFirestoreDoc(documentReference);
  return <p>{doc.data().x}</p>;
}

function Sample() {
  const [enabled, setEnabled] = useState(false);

  return (
    <>
      <button onClick={() => setEnabled(!enabled)}>toggle</button>
      {enabled ? <Data /> : <Placeholder />}
    </>
  );
}
```

Plus, the second way makes it much easier to use the new concurrent mode stuff, like [`useTransition`](https://reactjs.org/docs/concurrent-mode-reference.html#usetransition):

```jsx
function Data() {
  const documentReference = useFirebaseApp()
    .firestore()
    .collection("x")
    .doc("abcd");
  const doc = useFirestoreDoc(documentReference);
  return <p>{doc.data().x}</p>;
}

function Sample() {
  const [enabled, setEnabled] = useState(false);
  const [startTransition, isPending] = useTransition({ timeoutMs: 2000 });

  return (
    <>
      <button onClick={() => startTransition(setEnabled(!enabled))}>
        toggle
      </button>
      {isPending ? <MyLoadingSpinner /> : ""}
      {enabled ? (
        <Suspense fallback={"fetching data..."}>
          <Data />
        </Suspense>
      ) : (
        <Placeholder />
      )}
    </>
  );
}
```

**Comment by mlipscombe** [comment]
@jhuleatt after reflecting, I think you are right.  I would close this, but if the discussion from #166 will overflow to here, I'll leave it to you to close.

**Comment by jhuleatt** [comment]
Thanks for understanding, @mlipscombe. I'm going to close this for now, but willing to reopen if others comment here with some use cases we haven't thought of yet.

**Comment by dannybarinshtein** [comment]
@jhuleatt - I'm actually in a similar boat right now with this.

I am using the same component for both creating new, and updating existing documents. If i'm creating new documents I would want to avoid fetching the document. On top of that in my build I already foresee many situations like this.

You mentioned to add a check {if (doc.exists === true)} - but there are two major concerns here:

1. It is adding unnecessary reads to our app in such cases / additional requests that are just unnecessary.

2. We would have to overcomplicate error catching - in this case the most common one would be insufficient permissions for the read. 

If a user can create a new, but not read an existing document - the read would throw an insufficient permission error. While it is possible to add additional error boundaries it would simply make the app messier and messier at scale as far as i'm concerned.

A potential approach would be to have an additional prop to **ReactFireOptions**? In which case if the developer did accidentally add null / undefined then the behaviour would be as it is currently, and if the additional prop exists you know the developer is intending to have a conditional read.

Thoughts?

**Comment by dannybarinshtein** [comment]
Hey @jhuleatt - wondering what your thoughts on the above are?

**Comment by jhuleatt** [comment]
Hey @dannybarinshtein, sorry for the delay. Any chance you can provide a pared-down code sample to demonstrate? I think I understand you use case, and I'm pretty sure that the better solution is still to break things out into different components instead of passing a null query to `useFirestoreDoc`, but having a concrete example would make it easier to discuss.

**Comment by dannybarinshtein** [comment]
Mid writing up an example here I started to agree with you that it might be best to separate into smaller components.

Lets disregard this :) thanks for the feedback!

**Comment by danilowanner** [comment]
Splitting into multiple components is generally doable. However going with this approach will not allow to compose the hooks together, to encapsulate more complex behaviour. Something like:

```js
function useCurrentUser() {
  const [authUser, loading, error] = useAuthState(firebase.auth());
  const [documentReference, setDocumentReference] = useState<UserDocumentReference>();

  useEffect(() => {
    if(authUser && !loading && ! error) {
      setDocumentReference(getUserDocumentReference(authUser.uid))
    }
  }, [currentUserUid]);

  return useDocumentData<User>(documentReference);
}
```

In this example the desired document reference is only available once `useAuthState` returns the user.

Other than passing a `null | undefined` document reference while resolving the dependency, or splitting into two components for each hook consumer, how else can it be achieved?

Other libraries such as Apollo have some solutions. Apollo's `useQuery` supports a `skip` option, if set to `true` it will not execute the query. Also they have an alternative hook called `useLazyQuery ` which will not execute automatically, but can me triggered manually.
https://www.apollographql.com/docs/react/data/queries/#usequery-api
