### ISSUE TITLE
ClaimsCheck's return statement should be wrapped around React.Fragment (<> </>)

### ISSUE THREAD

**Issue by catrawalkar** [FirebaseExtended/reactfire#179]
### Version info

**React:** 16.9.0

**Firebase:** 7.2.0

**ReactFire:** 2.0.0-canary.d96bda4

**Other (e.g. Node, browser, operating system) (if applicable):**

### Steps to reproduce

If we use ClaimsCheck like this (without using fallback) or even AuthCheck which uses ClaimsCheck:
`
    <ClaimsCheck user={user} requiredClaims={{ isModerator: true }}>
        <span>
            Welcome, {user ? user.displayName : null}
        </span>
    </ClaimsCheck>

`

and requiredClaims are not met, it gave me error. This is probably because return statement in ClaimsCheck component is not wrapped in React Fragment as it is in AuthCheck's return statement.

### Expected behavior

When requiredClaims are not met, it should by default return null if Fallback is not mentioned.

### Actual behavior

When requiredClaims are not met and fallback is not mentioned, it gives error.

### Query

Also, what is the correct way to print Welcome User inside ClaimsCheck or AuthCheck ? I am using `const user = useUser()`
at the top and later referencing that `user` inside AuthCheck. What could be possible cleaner way of doing it?

**Comment by catrawalkar** [comment]
@jhuleatt  I tried to resolve this in #180 

Please check and comment your opinion

**Comment by jhuleatt** [comment]
Huh, today I learned that Suspense still works even if a fallback isn't given. I guess we should support that in our `*Check` components too. Thanks for the PR!

For your `useUser` question, can you please open another issue and provide an example?

**Comment by catrawalkar** [comment]
I didn't get what you mean by our `*Check` components. May be I can help in that and send a PR @jhuleatt

**Comment by jhuleatt** [comment]
Sorry for not being clear. By `*Check`, I mean `AuthCheck` and `ClaimsCheck`. Your PR #180 already fixed that.
