### ISSUE TITLE
Missing some packages in import switch statement?

### ISSUE THREAD

**Issue by hsubox76** [FirebaseExtended/reactfire#189]
Seems to be missing some of the more recently added packages in this switch statement (functions, etc.) - they seem to be in the enum just not in the switch.

https://github.com/FirebaseExtended/reactfire/blob/1fce6b94acf25f0fdc9c7dd647db8d417742e06f/reactfire/firebaseApp/sdk.tsx#L25

**Comment by jhuleatt** [comment]
Oops, I missed a few. The missing packages are:

- analytics
- functions
- messaging
- remote config

The workaround for now is to directly import the needed library (`import 'firebase/analytics'`) instead of lazy loading it.
