### ISSUE TITLE
Reactfire in a Expo React Native App

### ISSUE THREAD

**Issue by maxmayerhofer93** [FirebaseExtended/reactfire#190]
Hi Guys, 
i have seen the function on ReactDay.Berlin, and it was amazing how easy its looks. 

So I want to integrate ReactFire on my Expo app, but after include SuspenseWithPerf he says, 

> Error: No perf object off of Firebase. Did you forget to import 'firebase/performance' in a component?

Ans when I import it, he says:

> Can't find variable: IDBIndex.

What can I do to fix it ?:) 

Thanks

**Comment by maxmayerhofer93** [comment]
okay, i find out, 
you can replace SuspenseWithPerf with the react default Suspense, 
and so you don't need to add  _import 'firebase/performance'_

**Comment by calendee** [comment]
@maxmayerhofer93 Do you have a sample of this working?  I'm still struggling with this.

**Comment by calendee** [comment]
Nvm.  I got it working.
