### ISSUE TITLE
useFirestoreDocData doubles the read count

### ISSUE THREAD

**Issue by dannybarinshtein** [FirebaseExtended/reactfire#196]
Hello,

I came across an **/issue/** where I am getting charged for double the reads when using useFirestoreDocData to subscribe to data.

I created a custom hook to pass a user object like the below:

```js
const useUserData = () => {
  const firestore = useFirestore()
  const userAuth = useUser()

  const user = useFirestoreDocData(firestore().doc(`users/${userAuth.uid}`))
  
  return user
}
```

The way I am testing is only having one trigger to useFirestoreDocData throughout the whole app with the expectation to trigger only 1 read on app init, refreshing 4 extra times to generate 5 total reads, and then checking the firebase Usage tab.

I have changed the useFirestoreDocData to a none ReactFire snapshot subscription and am only getting charged for 1 read as oppose to useFirestoreDocData's 2 **/confirming/** that it has nothing to do with anything else in the app structure.

Any ideas on this?

As a side note I was hoping I could ask on how are ReactFire's subscriptions handled on page refresh / window close. Are they automatically unsubscribed or will they still be running? If they are still running are there any plans to implement a feature that would terminate them on such events / any suggestions on best practices for that?

### Version info

**React:** ^16.12.0
**Firebase:** ^7.6.1
**ReactFire:** ^2.0.0-canary.1fce6b9

**Comment by jhuleatt** [comment]
Hi @dannybarinshtein!

Regarding when unsubscribes happen: Reactfire subscriptions are cleaned up when the component using them unmounts.

Regarding double reads: This might be a Reactfire bug. I'll try to reproduce it

**Comment by dannybarinshtein** [comment]
Thanks Jeff,

Let me know if you need any help reproducing this.

As for the unsubscribes, I understand that Reactfire unsubscribes on Component unmounts, but those unmounts do not happen on window close or refresh as they can not access the browser context anymore.

To elaborate what would happen is a user would have subscriptions and then either close or reload the window where the unmount unsubscribes would not be able to fire.

An implementation along the lines of:
https://firebase.google.com/docs/reference/js/firebase.database.OnDisconnect

Unless I am missing something here and firebase does something similar behind the scenes that I am not aware of

**Comment by jhuleatt** [comment]
Unfortunately, Firestore doesn't have the same support for presence that the Realtime Database has. Can you please file a feature request against the core Firestore product with [this form](https://firebase.google.com/support/troubleshooter/report/features/)?

We have a documented workaround [here](https://firebase.google.com/docs/firestore/solutions/presence), although it has some [limitations](https://firebase.google.com/docs/firestore/solutions/presence#limitations).

**Comment by dannybarinshtein** [comment]
Thanks @jhuleatt  

The workaround would defeat the purpose, was more seeing how does a window close handle subscriptions, and if a snapshot update would trigger a read on a closed client.

Any luck reproducing the double read?

**Comment by jhuleatt** [comment]
Yes, I'm working on a PR to clean up ReactFire's subscription handling, and double reads should be solved as part of that.

**Comment by jhuleatt** [comment]
#210 was a refactor that significantly improved our reuse of subscriptions and should prevent double reads. Closing this out
