### ISSUE TITLE
Attempted import error: 'preloadAuth' is not exported from 'reactfire'.

### ISSUE THREAD

**Issue by preconception** [FirebaseExtended/reactfire#201]
"firebase": "^7.7.0",
   
     "react": "0.0.0-experimental-f42431abe",
 
    "reactfire": "^2.0.0-alpha.2"

Node v12.13.1

### Test case

https://github.com/seanaguinaga/sample

### Steps to reproduce

Clone

npm install

npm run start

### Expected behavior

App should compile

### Actual behavior

![image](https://user-images.githubusercontent.com/49764795/72684945-c2278a80-3a99-11ea-98e3-8f16502d2c05.png)

Not sure what's going on here?

I've done all the usual deletions, reinstalls, etc. to no avail

Unsure if this an issue with my machine or a reactfire thing?

**Comment by dannybarinshtein** [comment]
I believe you need to use the reactfire@canary installation to access the newer hooks

**Comment by jhuleatt** [comment]
correct, please `npm install reactfire@canary`

Sorry for the confusion @preconception! I'll make a note to update the `@next` release with a new alpha cut

**Comment by jhuleatt** [comment]
I've released a new alpha on `@next`
