### ISSUE TITLE
error: request "firebase-sdk-auth" is already in use.

### ISSUE THREAD

**Issue by wizawuza** [FirebaseExtended/reactfire#209]
### Version info
**React:**
    "react": "0.0.0-experimental-241c4467e",

**Firebase:**
    "firebase": "7.8.0",

**ReactFire:**
    "reactfire": "2.0.0-canary.e2f1b1f", <- this one is broken
    "reactfire": "2.0.0-canary.33f1e6a", <- this slightly older one works

In my custom hooks I use stuff like
`const user = useUser();`

When upgrading to the newest canary build, I get the error:

> error: request "firebase-sdk-auth" is already in use.

It's weird that I don't get it on localhost, but once I do firebase deploy --only hosting, it breaks on my public server.

Downgrading back to canary.33f1e6a seems to fix it.

**Comment by jhuleatt** [comment]
Hi @wizawuza thanks for reporting this!

Do you have time to provide a reproducing example in StackBlitz? This might be a good starting point: https://stackblitz.com/fork/reactfire-sample

**Comment by wizawuza** [comment]
@jhuleatt 
Alas, I cannot reproduce it on stackblitz but it's still an error on my end while downgrading (and only downgrading).. sorry =\
closing for now

**Comment by jhuleatt** [comment]
Thanks for trying!

On the bright side, #210 is a significant rework of the internals of reactfire and will likely get rid of this issue
