### ISSUE TITLE
Unable to resolve "./index.esm-e07042b9.js" from "node_modules/reactfire/cjs/index.js"

### ISSUE THREAD

**Issue by josermorales** [FirebaseExtended/reactfire#214]
### Version info

**React:16.9.0

**Firebase:7.8.5

**ReactFire:2.0.0-rc.0

**Other (e.g. Node, browser, operating system) (if applicable):**

OS: Mac OS 10.15.3

### Steps to reproduce

1. New react project (react native expo in my case)
2. yarn add reactfire
3. yarn add firebase
4. Wrap app in FB provider with config
5. Start server
6. Unable to resolve "./index.esm-e07042b9.js" from "node_modules/reactfire/cjs/index.js"

### Expected behavior

react hooks available

### Actual behavior

Unable to resolve "./index.esm-e07042b9.js" from "node_modules/reactfire/cjs/index.js"

**Comment by jamesdaniels** [comment]
I have a good handle on what this might be, will get it fixed in rc.1. Thanks for filing the issue!

**Comment by jamesdaniels** [comment]
Should be addressed in `2.0.0-rc.1` which we just cut to NPM, if you have any other problems just open another issue.
