### ISSUE TITLE
AuthCheck behaviour & sever timestamps

### ISSUE THREAD

**Issue by dannybarinshtein** [FirebaseExtended/reactfire#225]
Hey guys,

I have a few questions / comments / requests

1.  For the AuthCheck component is there any way to have (or request a future implementation) a check for emailVerified - I believe it would be quite beneficial to not render the logged-in routes if an email verification is required.

2. What is the recommended approach to handle UI updated after email verification? the AuthCheck (nor the useUser) does not listen to a change to the emailVerified value on the user.

The default firebase.auth().onAuthStateChanged will pick up on the emailVerified change with the addition of the code below, making updating the UI simple

(where the user is the return of useUser())

```
await user.getIdToken(true)
await user.reload()
```

3. How can we add a server timestamp to our doc? neither firebase.firestore.Timestamp.fromDate(new Date()) nor firebase.firestore.FieldValue.serverTimestamp() seem to work on creation.

Thanks in advance!

**Comment by jhuleatt** [comment]
Hi @dannybarinshtein! Thanks for reaching out.

1. Yes, that sounds like a valid feature request! Can you please file that as a separate issue so that we can have a more focused discussion about what the API might look like?
1. I believe you can do this in a useEffect hook, and it would look something like this:
    ```js
    function MyComponent() {
      const user = useUser();
    
      useEffect(async () => {
        await user.getIdToken(true);
        await user.reload();
      }, [user]);
    
      // ...
    }
    ``` 
    If that doesn't work, can you please create a separate issue to discuss?
1. It looks like we have a bug. I was able to repro, so I filed #227

**Comment by dannybarinshtein** [comment]
Thanks Jeff - Opened up #230 that builds up more on #1 and #2 as I believe both are closely related
