### ISSUE TITLE
useFirestoreDocData creates 'Uncaught FirebaseError: Missing or insufficient permissions'  vs useFirestoreDocDataOnce 

### ISSUE THREAD

**Issue by 16oh4** [FirebaseExtended/reactfire#228]
### Version info

**React:**  
    "react": "^0.0.0-experimental-235a6c4af",
    "react-dom": "^0.0.0-experimental-235a6c4af",

**Firebase:** 7.8.2

**ReactFire:** ^2.01

**Other (e.g. Node, browser, operating system) (if applicable):**

Browser:
Google Chrome | 80.0.3987.132 (Official Build) (64-bit) (cohort: 80_Win_132)
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | Windows 10 OS Version 1903 (Build 18362.267)
JavaScript | V8 8.0.426.26

### Steps to reproduce

I have a protected route in App.js using Suspense and AuthCheck
```jsx
<App>
<BrowserRouter>
<Suspense fallback={<p>Loading</p>}>
                  <AuthCheck 
                    fallback={<p>Please login</p>}
                  >
                    <Route exact path="/home">
                        <Home/>
                    </Route>    
                  </AuthCheck>
                </Suspense> 
</BrowserRouter>
</App> 
```

When the user logs in, by clicking a button, the handler executes the following:

```jsx
auth.signInWithEmailAndPassword(email, password)
        .then(userCredential => {
            //TODO FIX REDIRECT TO HOME
            // console.log(JSON.stringify(userCredential));
            history.push('/home')
        })
```

Using "react-router-dom": "^5.1.2", history.push('/home') redirects to the Protected route upon the userCredential promise.

In the Home component, I am merely listening to a document based on the user's uid and displaying the results on screen. I have tried defining startsWithValue options to no avail (for the userDocData)

```jsx
const user = useUser();

    const userDocRef = useFirestore().collection('users').doc(user.uid);
    const userDocData = useFirestoreDocData(userDocRef);
```

For further information, I have a firestore security rule to allow only authenticated reads on the user document:

```
match /users/{document} {
      allow read: if (request.auth.uid != null); // Allow logged in users to see data
```

### Expected behavior

The user is redirected to the Home page and the document data is loaded with no issues.

### Actual behavior

Upon clicking login in the Login page, the user is redirected to a white screen with the following console error:

Chrome javascript Console
```
Uncaught FirebaseError: Missing or insufficient permissions.
    at new FirestoreError (http://localhost:3000/static/js/2.chunk.js:419:24)
    at JsonProtoSerializer.fromRpcStatus (http://localhost:3000/static/js/2.chunk.js:18823:12)
    at JsonProtoSerializer.fromWatchChange (http://localhost:3000/static/js/2.chunk.js:19376:38)
    at PersistentListenStream.onMessage (http://localhost:3000/static/js/2.chunk.js:15347:39)
    at http://localhost:3000/static/js/2.chunk.js:15258:22
    at http://localhost:3000/static/js/2.chunk.js:15308:18
    at http://localhost:3000/static/js/2.chunk.js:2012:14
```

Workarounds:
**What is peculiar here is that using _useFirestoreDocDataOnce_ effectively removes the error**
**Rewriting the firestore rule to _allow read: if true_ also removes the error.**

**Comment by jhuleatt** [comment]
@16oh4 this will be a tough one to diagnose without a more complete sample. Any chance you can create a minimal version of your app in StackBlitz or CodeSandbox so that we can see the full app code needed to reproduce the problem?

**Comment by 16oh4** [comment]
> @16oh4 this will be a tough one to diagnose without a more complete sample. Any chance you can create a minimal version of your app in StackBlitz or CodeSandbox so that we can see the full app code needed to reproduce the problem?

I apologize but I am working on an enterprise application.

This error is caused in every file I try to use it in. I've noticed the error only happens with listener functions like useFirestoreDocData and useFirestoreCollectionData, but using useFirestoreDocDataOnce and useFirestoreCollectionDataOnce both work under the same conditions.

The error only occurs when navigating to the page using history.push (PAGE LINK HERE) provided by React Router. When refreshing the page with the useFirestoreCollectionData or DocData call, there are no errors.

**Comment by howitzer-industries** [comment]
@jhuleatt I am having a similar issue, there seems to be an issue making a firestore request that requires authentication immediately after signing in. Seems like the token isn't getting sent the first time. If you reload the page after signing in, it works fine.

I made a sample that exhibits it. The repo is here: https://github.com/howitzer-industries/reactfire-auth . Here's a link to a code sandbox: https://codesandbox.io/s/wizardly-wing-s5eme . You can use +1 555 555 5555 as the phone number and 123456 as the code. To recreate it, sign in and then it should error saying "missing or insufficient permissions". If you reload, it will work fine. You can sign out again and see it happen again when you sign back in. It errors right after sign in ~70% of the time, in my testing.

**Comment by howitzer-industries** [comment]
Digging into it further, seems like the `react-firebaseui` callbacks aren't firing either. Maybe it's getting unloaded by `AuthCheck` before firing or it doesn't play nice with async rendering? Going to switch back to plain firebase, but would be curious to hear if anyone figures out what the issue is.

**Comment by mrmckeb** [comment]
I can confirm this happens on the second sign-in of any account - but doesn't happen if you sign in with a different account.

Sign-in User A > Sign Out > Sign-in User B > Sign Out > Sign-in User A > Error

**Comment by mrmckeb** [comment]
I actually think this may be related to #256.

Locally, I added `preloadedObservables.delete(observableId)` in the cleanup function of `useObservable` and this stopped the error form r

**Comment by nelreina** [comment]
I have similar issue with sign-out as @mrmckeb the difference is I get this error with the same user. To prevent this error users needs to refresh their browser. The other thing is I am not using the useObservable hook neither. Just useFirestoreCollectionData and the Authcheck component.

Our app was build without using reactfire by creating our own hooks to handle firebase and firestore. By implementing This  reactfire library our the code is more elegant and scalable. At this moment in time this is an show stopper issue for users.

It seems like when the user sign's-out it does not cleanup everything, and when the user sign-in again without refreshing the browser the old token or session is still in memory.

**Comment by mrmckeb** [comment]
@nelreina the useObservable`hook is also used inside of `useFirestoreCollectionData` which is why you hit this.

I found a very temporary workaround, which might help you. I run it after logout.
```ts
export const clearFirestoreCache = () => {
  const map = globalThis['_reactFirePreloadedObservables'];
  Array.from(map.keys()).forEach(
    (key) => key.includes('firestore') && map.delete(key),
  );
};
```

It may cause more problems for you though, depending on how your app is built - but for me, it works as logged out users don't see anything from the database.

**Comment by nelreina** [comment]
@mrmckeb Thank you I will try it

**Comment by jhuleatt** [comment]
Thanks for the repros and additional information!

`AuthCheck` only renders children when a `user` object is returned from `useUser`, so I thought `useUser` might be the culprit, but after taking a look it seems to be working correctly. I'm wondering if a Firestore query (cached in the `_reactFirePreloadedObservables` cache) initiated by one user can't be continued by another user. Maybe ReactFire needs to wipe out the cache (or at least parts of it) on auth state changes, similar to @mrmckeb's workaround.

I wasn't able to dig into this any more today, but I'll take another look tomorrow!

**Comment by jhuleatt** [comment]
Thoughts from @jamesdaniels : maybe we handle permission denied errors as a special case, if we encounter, clear the current value out of the cache and retry once

Or we can look into subscribing to Auth state on a deeper level

**Comment by mrmckeb** [comment]
Interesting @jhuleatt - I guess the other case that would need to be handled there is when you you might expect permission denied? However, I think most applications would be developed in a way where that shouldn't be an issue.

**Comment by jhuleatt** [comment]
Agreed, we still need to surface permission denied when it is accurate.

I'm also wondering if this issue might be related to #249

**Comment by ChrisBrownie55** [comment]
Is this going to be fixed soon? I'm planning on trying @mrmckeb's workaround for now.

**Comment by hubgit** [comment]
> we still need to surface permission denied when it is accurate.

Is there an issue open for this? It was a bit surprising to get an Uncaught FirebaseError when accessing a document without permission.
