### ISSUE TITLE
Usage with Database Emulators

### ISSUE THREAD

**Issue by prescottprue** [FirebaseExtended/reactfire#235]
### Version info

**React:** ^16.3.0

**Firebase:** ^7.12.0

**ReactFire:** ^2.0.2

**Other (e.g. Node, browser, operating system) (if applicable):**

### Steps to reproduce

```jsx
import React, { Suspense } from 'react'
import { FirebaseAppProvider } from 'reactfire'

const firebaseConfig = { /* standard firebase config */ }
// Enable Real Time Database emulator (works great!)
firebaseConfig.databaseURL = `http://localhost:9000?ns=${firebaseConfig.projectId}`

function App({ routes }) {
  // Enable Firestore emulator (does not work)
  // NOTE: Currently requires loading Firestore which must be done below Provider
  // const firestore = useFirestore()
  // firestore.settings({
  //  host: 'localhost:8080',
  //  ssl: false
  //})

  return (
      <FirebaseAppProvider firebaseConfig={firebaseConfig}>
        <Suspense fallback={<div>Loading...</div>}>
          <SomeComponent />
        </Suspense>
      </FirebaseAppProvider>
  )
}

function SomeComponent() {
  // Enable Firestore emulator
  // NOTE: Must be done in any component using Firestore and called on each render
  const firestore = useFirestore()
  firestore.settings({
    host: 'localhost:8080',
    ssl: false
  })
  return <div> Some</div>
}
```

This can currently be done on the lower component levels, but needs to be repeated in all of your components that are using Firestore if you want to keep the benefit of lazy loading the SDK when needed. Also, it will be called each time each component is rendered. If these settings are left out of any component the following error appears when using any Firestore method:

```
index.cjs.js:367 Uncaught FirebaseError: Firestore has already been started and its settings can no longer be changed. You can only call settings() before calling any other methods on a Firestore object.
```

### Expected behavior

Be able to set this setting and not have to wait for when `useFirestore` is called. That way this can be done at a top level without yet lazy loading the Firestore section of the SDK (as can be done with the RTDB config). Also, it will prevent needing to repeat this within 

Maybe if there was an extra prop that, when set to true, enables the firestore emulator when it is loaded:

```jsx
 <FirebaseAppProvider firebaseConfig={firebaseConfig} firestoreEmulator>
```

### Actual behavior

Firestore section of SDK needs to be imported to set emulator settings. If there is already a way to do this, having that documented in a section about using emulators would probably save folks a bit of time

**Comment by jhuleatt** [comment]
@prescottprue thanks for trying out ReactFire with the emulators! Luckily, ReactFire already supports a couple of ways to do this:

The `preloadFirestore` function allows you to do setup work before the Firestore SDK is made available to any component that consumes it. In the sample, we use it to enable persistence:

https://github.com/FirebaseExtended/reactfire/blob/848eaa3c6993221c52d81c86c68700130a2d27f2/sample/src/App.js#L41-L43

Alternatively, if you want to use [@firebase/testing](https://www.npmjs.com/package/@firebase/testing), you can initialize the test SDK and pass it to FirebaseAppProvider as a prop instead of `firebaseConfig`: `<FirebaseAppProvider firebaseApp={app}>`. This is what we do in the ReactFire tests.

Hope this helps! We definitely need to get this in the docs.

**Comment by prescottprue** [comment]
Thanks for all the info and the quick response! Being able to pass the initialized app will definitely help for testing.

It would still be nice to have a way of doing this without actually starting the loading the SDK since using `preloadFirestore` would still need to be placed into any route needing firestore. I was thinking about working into a parent route, but it would be nice not to have to do that. I'm hoping to still benefit from the lazy loading of the SDK when using `useFirestore`

Context: For some time I been using `reactfire` as the basis for [generator-react-firebase](https://github.com/prescottprue/generator-react-firebase) when opting out of redux. Firestore is only needed on certain routes, so the goal would be to set the config one time instead of having the preload logic on each route.

**Comment by marianrick** [comment]
Thanks for the hint to use `preloadFirestore()`. But I am confused how to use it to setup my local emulator settings.

Currently I am using the preloading like suggested in your example App with the exact same code like you have quoted @jhuleatt . How can I add a `.settings({host: 'localhost:8080', ssl: false})` to it?

I have tried the following, but it does not work with enablePersistence (which I would love to test as well):
```
preloadFirestore(firebaseApp, firestore => { 
   return firestore().settings({host: 'localhost:8080', ssl: false}).enablePersistence(); 
 }),
```

Do you have any suggestions of how to combine the local emulator setting with enablePersistence?

**Comment by marianrick** [comment]
Thanks in advance for any thought in this, but I have solved it myself:

```
preloadFirestore(firebaseApp, firestore => { 
  const initalizedStore = firestore();
  // lets only use local emulator in dev env
  if (process.env.NODE_ENV) {
    initalizedStore.settings({host: 'localhost:8080', ssl: false});
  }
  await initalizedStore.enablePersistence();
  return initalizedStore;
 }),
```

I just missed some basic knowledge about this syntax. Thanks for the good example App 🙌
