### ISSUE TITLE
Type 'App' has no properties in common with type 'PreloadOptions<() => Firestore>'

### ISSUE THREAD

**Issue by seanaguinaga** [FirebaseExtended/reactfire#236]
```export function useFirebase() {
  const firebaseApp = useFirebaseApp();

  // Our components will lazy load the
  // SDKs to decrease their bundle size.
  // Since we know that, we can start
  // fetching them now

  const preloadSDKs = () => {
    return Promise.all([
      preloadFirestore(firebaseApp),
      preloadDatabase(firebaseApp),
      preloadStorage(firebaseApp),
      preloadAuth(firebaseApp)
    ]);
  };

  const preloadData = async () => {
    const user = await preloadUser(firebaseApp);
    console.log("logged out", user);

    if (user) {
      preloadFirestoreDoc(
        (firestore: any) => firestore.doc("count/counter"),
        firebaseApp
      );
    }
  };

  return {
    preloadSDKs,
    preloadData,
    firebaseApp
  };
}
```

![image](https://user-images.githubusercontent.com/15254340/77569008-c059b900-6e86-11ea-97a2-aa4793589b48.png)

I'm assuming I'm just not initializing something right?

**Comment by seanaguinaga** [comment]
![image](https://user-images.githubusercontent.com/15254340/77569396-63aace00-6e87-11ea-9a7c-fb89fd653f66.png)
I see now you changed how this is written in the sample. 

How the heck should I/would I type this?

Should I just use ```any``` for now?

**Comment by jhuleatt** [comment]
Hey @seanaguinaga our sample is out of date here. Apologies.

This is the signature for `PreloadOptions`: https://github.com/FirebaseExtended/reactfire/blob/848eaa3c6993221c52d81c86c68700130a2d27f2/reactfire/firebaseApp/sdk.tsx#L98-L101

so to call `preloadFirestore`, you'd do:

```tsx
preloadFirestore({firebaseApp});
```

The `setup` field lets you do things with the Firestore library (or other Firebase libraries) before they're exposed to any component that uses them. This is useful for things like [`enablePersistence`](https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#enable-persistence) which has to be called before any reads or writes happen.

**Comment by jhuleatt** [comment]
Here's an example from a test: https://github.com/FirebaseExtended/reactfire/blob/8a54d42d9e07cc767edf24b9189e570a1eeaeb47/reactfire/firestore/firestore.test.tsx#L59-L62

**Comment by jhuleatt** [comment]
I've created #237 to remind us to update the docs
