### ISSUE TITLE
Update docs & sample for preloadSDK functions

### ISSUE THREAD

**Issue by jhuleatt** [FirebaseExtended/reactfire#237]
Now that the preload functions take a `PreloadOptions` argument, the docs and sample are out of date

**Comment by RodyGL** [comment]
Hi! I was trying to use the updated preloadFirestore to setup emulators and use this config --> [https://firebase.google.com/docs/emulator-suite/connect_and_prototype?database=Firestore#instrument_your_app_to_talk_to_the_emulators](url) but it's not working. Any idea why? I tried without reactfire and works fine.

**Using reactfire v2.0.3**

**Comment by ljrodriguez1** [comment]
Hello i am not able to preload firestore, i am trying to enable persistance as follows
` preloadFirestore({
    setup: firestore => firestore().enablePersistence()
  });
`
I would like some help to enable this option.

**Comment by elliotcw** [comment]
This is my working code. You likely need to pass in` firebaseApp`.

```
  const firebaseApp = useFirebaseApp();

  preloadFirestore({
    firebaseApp,
    setup: (firestore) => {
      firestore().settings({ ignoreUndefinedProperties: true });
    },
  });
```

**Comment by jhuleatt** [comment]
sample has been updated: https://github.com/FirebaseExtended/reactfire/blob/ecb499677f419882b6d3e49da4c1ba85d0a07ae5/example/withSuspense/App.tsx#L26-L31
