### ISSUE TITLE
Recognizing All Contributors

### ISSUE THREAD

**Issue by jhuleatt** [FirebaseExtended/reactfire#241]
The ReactFire repo now uses the [All Contributors spec](https://allcontributors.org/docs/en/overview) to recognize the contributions of everyone that has helped out with ReactFire v2.

**Comment by jhuleatt** [comment]
To add yourself to the contributors list, invoke the bot:

@all-contributors, please add @jhuleatt for code, doc, example, ideas, tutorial, talk

**Comment by jhuleatt** [comment]
Testing the bot:

@all-contributors, please add @jhuleatt for code

**Comment by jhuleatt** [comment]
@all-contributors please add @jhuleatt for code

**Comment by jhuleatt** [comment]
Working through some permissions issues with the bot's PR https://github.com/FirebaseExtended/reactfire/pull/242

**Comment by w3bdesign** [comment]
@all-contributors, please add @w3bdesign for code

**Comment by w3bdesign** [comment]
@all-contributors please add @w3bdesign for code

**Comment by prescottprue** [comment]
@all-contributors please add @prescottprue for code
