### ISSUE TITLE
useFunctionsEmulator() Supported?

### ISSUE THREAD

**Issue by seanaguinaga** [FirebaseExtended/reactfire#262]
Hello

Is useFunctionsEmulator Supported?

It does not seem to function at all when used.

```
  let functions = useFunctions;

  functions().useFunctionsEmulator("http://localhost:5001");

  let test = functions().httpsCallable("authOnCreate");
```

Am I simply calling it wrong?

**Comment by seanaguinaga** [comment]
Ah. I was getting an error because it wasn’t preloaded. 

I occasionally get an error if things don’t load in the right order or if functions are not fully loaded in time. Is there a way to force the “availability “ of certain parts of reactfire?

**Comment by hubgit** [comment]
This works for me:

```js
  preloadFunctions({
    setup: (functions) => {
      functions().useFunctionsEmulator('http://localhost:5001')
    },
  })
```

**Comment by seanaguinaga** [comment]
Thank you @hubgit !
