### ISSUE TITLE
Unable to set a region with useFunctions()

### ISSUE THREAD

**Issue by jeff-kroot** [FirebaseExtended/reactfire#267]
Currently, we have to do the following to specify the region with `useFunctions()`:

```jsx
const functions = useFunctions();
functions.region_ = 'europe-west1';
```

This does not seem like the way it should work (also seeing it's undocumented).

Maybe something like the following:

```jsx
const functions = useFunctions('europe-west1');
// or
const functions = useFunctions()('europe-west1');
// or
const functions = useFunctions({ region: 'europe-west1'});
```

**Comment by elliotcw** [comment]
I've recently moved to `"firebase": "^7.24.0",`  and have had to change this a bit. Now you need to drop the dangling underscore on region.

So
```
const functions = useFunctions();
functions.region = 'europe-west1';
```
