### ISSUE TITLE
.where() "!=" ?

### ISSUE THREAD

**Issue by windsterx** [FirebaseExtended/reactfire#283]
.where() doesnt support "!=" as its second argument?? 
it gives me error FirebaseError: Invalid value "!=" provided to function Query.where() for its second argument. Acceptable values: <, <=, ==, >=, >, array-contains, in, array-contains-any
.where("captial","!=","")

**Comment by jhuleatt** [comment]
Hey @windsterx, sorry for the slow response. That feature was added in [`7.21.0`](https://firebase.google.com/support/release-notes/js#version_7210_-_september_17_2020) of the Firebase SDK, so it's likely you were referencing an older version in your package.json file.
