### ISSUE TITLE
Publish v2.0.4

### ISSUE THREAD

**Issue by hubgit** [FirebaseExtended/reactfire#284]
Would it be possible to publish [v2.0.4](https://github.com/FirebaseExtended/reactfire/releases/tag/v2.0.4) to the npm registry? Currently the latest published version is v2.0.3, from 7 months ago.

**Comment by soydulceangelina** [comment]
Hello,what I did was installing directly from GitHub on the master branch, like this:

```
"reactfire": "FirebaseExtended/reactfire#master"
```

**Comment by hubgit** [comment]
> ```
> "reactfire": "FirebaseExtended/reactfire#master"
> ```

How does that work when there's no `dist` directory in the source code, and package.json contains `"main": "dist/index.js"`?

**Comment by jamesdaniels** [comment]
Closing as outdated as we've moved onto the next release. Sorry about the CI/CD issues gumming things up.
