### ISSUE TITLE
Support firebase v8.0.0

### ISSUE THREAD

**Issue by hubgit** [FirebaseExtended/reactfire#287]
https://firebase.google.com/support/release-notes/js#version_800_-_october_26_2020

v8.0.0 of `firebase` contains a breaking change:

```js
import * as firebase from 'firebase/app'
```

should now be

```js
import firebase from 'firebase/app'
```

Adding `firebase` ~8 as a peerDependency would probably be a good idea.

**Comment by fronbasal** [comment]
I tried fixing this, unfortunately most of the tests break and require fixing beyond my knowledge of TypeScript (or JavaScript, for that matter).

**Comment by DenisGorbachev** [comment]
This is a blocker for using `reactfire`.

@jhuleatt Would highly appreciate if you could take a look - maybe it's just a quick fix :)

**Comment by fronbasal** [comment]
Absolutely! I manually downgraded firebase to 7, but that excludes a couple of neat features :(

**Comment by Diveafall** [comment]
Following the quick-start guide faces you with the error described above. Would be great if there was a note written somewhere that would make you aware of the problem before it arrives.
