### ISSUE TITLE
Access has been blocked by CORS policy

### ISSUE THREAD

**Issue by germanfr** [FirebaseExtended/reactfire#304]
Hi! I'm getting a **CORS** error when trying to sign in with a user from Chrome. It works when I use Firefox.

### Version info

**React:** 16.13.0
**Firebase:** 8.1.1
**ReactFire:** 3.0.0-rc.0
**Chrome:** 87

### Test case

This is my view code. `<Form/>` is the form component and returns the correct email and password.

```tsx
import * as React from 'react';
import { useAuth } from 'reactfire';

import { Form } from './Form';


const SignIn = props => {
	const auth = useAuth();

	const handleSubmit = (email, password) => {
		console.log("email: " + email, "password: " + password);
		auth.signInWithEmailAndPassword(email, password).then((user) => {
			console.log("Signed in", user);
		})
		.catch((error) => {
			let errorCode = error.code;
			let errorMessage = error.message;
			console.error(errorCode, errorMessage);
		});
	};

	return <Form onSubmit={handleSubmit} />;
};

export { SignIn };
```

### Steps to reproduce

I followed a simplified version of [this example](https://github.com/FirebaseExtended/reactfire/blob/master/docs/use.md#combine-auth-firestore-and-cloud-storage-to-show-a-user-profile-card) from the documentation.

### Expected behavior

To work. 

I don't know if I'm doing something wrong or there is something missing.

### Actual behavior

**Chrome console:**

```
Access to XMLHttpRequest at 'https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=XXXXXXX'
from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't
pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://localhost:3000'
that is not equal to the supplied origin.

auth/network-request-failed A network error (such as timeout, interrupted connection or unreachable host) has occurred.

auth.esm.js:219 POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=XXXXXXX net::ERR_FAILED
```

**Comment by jamesdaniels** [comment]
So what strikes me about this error message is `https://localhost:3000` vs `http://localhost:3000`, http**sssssss**, did you maybe put `localhost:3000` into your allowed auth domains in either the console or your firebase config? I don't think you need to do this as localhost is generally special-cased w/re to sandboxing.

**Comment by germanfr** [comment]
Thank you! That was it! I'm sorry I didn't catch that up.

For the record, to run react on `localhost` with https I had to add `HTTPS=true` to the `.env` file. Otherwise it wouldn't work.


PS: I didn't add localhost in the Firebase console. It was already there just as "localhost" without the port and protocol.
