### ISSUE TITLE
preloadFirestore param

### ISSUE THREAD

**Issue by stevenkaspar** [FirebaseExtended/reactfire#312]
https://github.com/FirebaseExtended/reactfire/blob/848eaa3c6993221c52d81c86c68700130a2d27f2/sample/src/App.js#L41

I think this should be `preloadFirestore({ firebaseApp }, (firestore) => {`

I get undefined `name` when following docs example

**Comment by jhuleatt** [comment]
Hey @stevenkaspar, looks like you're referencing an older version of the sample. The current version calls it correctly: https://github.com/FirebaseExtended/reactfire/blob/8d36acdbfa69afbdf38c529abe7ac96bc9a83715/example/withSuspense/App.tsx#L26-L31

Was there a spot in the docs that linked you to the old version? If so, please let us know so we can clean that up

**Comment by guytepper** [comment]
Hey @jhuleatt, I got to the old version from https://github.com/FirebaseExtended/reactfire/issues/235#issuecomment-602695851. 
It'd be nice to have the reference updated over there :]
