### ISSUE TITLE
Query complete collection.

### ISSUE THREAD

**Issue by ljrodriguez1** [FirebaseExtended/reactfire#313]
Hello i was trying to do this.
`
const todosRef = useFirestore().collection('todoList').get()  
`
`
const todos = useFirestoreDocData(todosRef);
`
But i was not able. i think it would be a nice feature to have the option to query an entire collection and watch for changes on it.

Then i realise that maybe the correct intention of Firestore usage is to have a document with a list.

Can the first idea be acomplish?, is the second idea a better aproach? what would happend if for example this is a chat with millions of message, i assume the second idea would not scale.

Any suggestion would be nice, i have been loving this package, and i think that maybe the option to query the whole colection would be usefull.

**Comment by jhuleatt** [comment]
Hey @ljrodriguez1, glad to hear you figured it out. Here's an example from the demo app in this repo of using `useFirestoreCollectionData`:

https://github.com/FirebaseExtended/reactfire/blob/8d36acdbfa69afbdf38c529abe7ac96bc9a83715/example/withoutSuspense/Firestore.tsx#L37-L43

`useFirestoreCollectionData` uses `onSnapshot` under the hood, so it will have the same streaming behavior as the [normal Firebase JS SDK](https://firebase.google.com/docs/firestore/query-data/listen#listen_to_multiple_documents_in_a_collection). Here are some docs on how billing works for listeners: https://firebase.google.com/docs/firestore/pricing#listens.
