### ISSUE TITLE
Firebase storage

### ISSUE THREAD

**Issue by hewseph** [FirebaseExtended/reactfire#333]
How do you get and create with firebase storage?

**Comment by jhuleatt** [comment]
Hi @hewseph, check out the `example` directory to see how to use Storage with ReactFire. 

get:

https://github.com/FirebaseExtended/reactfire/blob/9d96d92d212fbd616506848180e02e84d4866409/example/withoutSuspense/Storage.tsx#L51-L60

upload:

https://github.com/FirebaseExtended/reactfire/blob/9d96d92d212fbd616506848180e02e84d4866409/example/withoutSuspense/Storage.tsx#L23-L49
