### ISSUE TITLE
Suggested signature cleanup in example; side effect vs. hook

### ISSUE THREAD

**Issue by webbertakken** [FirebaseExtended/reactfire#337]
Hi there, and thanks for this great project! 
I especially like how it keeps the signature for small projects very tidy.

On topic; I was looking through the code and some of the examples and spotted this [todo](https://github.com/FirebaseExtended/reactfire/blob/252b60781086d657e4d43fa12237e0a068e395f1/src/auth.tsx#L9) and another [todo](https://github.com/FirebaseExtended/reactfire/blob/252b60781086d657e4d43fa12237e0a068e395f1/src/auth.tsx#L25). To practice I had a look at it and thought about how I would solve this if it were my project. I'm here to learn so I'd love to hear your feedback on the approach.

#### Problem

The problem here seems to be about some functions that have the signature of both a hook and as a regular function outside of the react tree, injecting context through a parameters. I would argue this on itself is an anti-pattern, and the solution may be simple if I'm not mistaken;

#### Case `preloadUser`

Looking at `preloadUser` we're dealing with a side effect, that would always be called from `useEffect` and never as a contextual hook like `usePreloadUser`. As far as I can see it's not used as a hook now either.

Suggested change to [preloadUser](https://github.com/FirebaseExtended/reactfire/blob/252b60781086d657e4d43fa12237e0a068e395f1/src/auth.tsx#L8)

```diff
- export function preloadUser(options?: { firebaseApp?: firebase.app.App }) {
-    // TODO: Find an alternative that doesn't break the rules of hooks (conditional hook call)
-   const firebaseApp = options?.firebaseApp || useFirebaseApp();
- 
+ export function preloadUser(firebaseApp: firebase.app.App) {
    return preloadAuth({ firebaseApp }).then(auth => {
      const result = preloadObservable(user(auth()), `auth:user:${firebaseApp.name}`);
      return result.toPromise();
    });
  }
```

#### Case `useUser`

- For `useUser` the opposite applies, it would always be used as a hook en never need to be provided an auth object.

There is one reference that violates this signature;

![image](https://user-images.githubusercontent.com/20756439/108924513-0c831f80-763b-11eb-9da3-fe033cf98462.png)

Since the reference is a component that, I would argue that it would realistically never used outside of `FirebaseAppProvider`, and suggest the following changes:

to [AuthCheck](https://github.com/FirebaseExtended/reactfire/blob/252b60781086d657e4d43fa12237e0a068e395f1/src/auth.tsx#L97)
```diff
- export function AuthCheck({ auth, fallback, children, requiredClaims }: AuthCheckProps): JSX.Element {
+ export function AuthCheck({ fallback, children, requiredClaims }: AuthCheckProps): JSX.Element {
  const { data: user } = useUser();

  if (user) {
    return requiredClaims ? (
      <ClaimsCheck user={user} fallback={fallback} requiredClaims={requiredClaims}>
        {children}
      </ClaimsCheck>
    ) : (
      <>{children}</>
    );
  } else {
    return <>{fallback}</>;
  }
}
```

to [useUser](https://github.com/FirebaseExtended/reactfire/blob/252b60781086d657e4d43fa12237e0a068e395f1/src/auth.tsx#L24)
```diff
/**
 * Subscribe to Firebase auth state changes, including token refresh
 *
- * @param auth - the [firebase.auth](https://firebase.google.com/docs/reference/js/firebase.auth) object
 * @param options
 */
- export function useUser<T = unknown>(auth?: firebase.auth.Auth, options?: ReactFireOptions<T>): ObservableStatus<firebase.User> {
-  // TODO: Find an alternative that doesn't break the rules of hooks (conditional hook call)
-  auth = auth || useAuth();
-
-  if (!auth) {
-    throw new Error('firebase.auth not found');
-  }
+ export function useUser<T = unknown>(options?: ReactFireOptions<T>): ObservableStatus<firebase.User> {
+  auth = useAuth();

  const observableId = `auth:user:${auth.app.name}`;
```

Finally the error could be shown in `useAuth();` as you would always expect `firebase.auth` to be in scope.

If you agree with these changes I'd be happy to send a PR. If not, I'd love to learn what mistakes I'm making.
Thank you for your consideration.

**Comment by jhuleatt** [comment]
Hi @webbertakken, thanks for the thoughtful issue. We'd definitely be open to a PR with these changes if you're still willing.

- `preloadUser`: I agree with this one wholeheartedly
- `AuthCheck` and `useAuth`: Short answer: I agree with your conclusion. Long answer: We had originally left the `auth` argument in to allow someone to potentially check someone's signed-in status across multiple Firebase projects. However, I think that's a very niche case, and probably not worth violating the rules of hooks for. Instead, in the future we could always consider adding a second `useMyOwnAuth` hook that takes `auth` as an argument, or just encourage people to add another `FirebaseAppProvider`.

**Comment by webbertakken** [comment]
Wow that was fast @jhuleatt! I didn't even get a chance 😄

Thanks a lot!
