### ISSUE TITLE
Observable hasEmitted with useUser Hook never gets true

### ISSUE THREAD

**Issue by mnlfischer** [FirebaseExtended/reactfire#342]
**React:** 17.0.1

**Firebase:**8.2.9

**ReactFire:**3.0.0rc.0

### Test case

https://codesandbox.io/s/musing-sky-dt1zi?file=/src/App.js

### Steps to reproduce

Use useUser in a component and load the page for first time. Try to use a loading state with
`if (status === "loading" || hasEmitted === false)` and see that hasEmitted never gets true, so the loading state never disappears.

Note: When you use hot reloading, all rerenders are not affected by this bug.

### Expected behavior
hasEmitted should be true after some time.

### Actual behavior

hasEmitted is always false.

**Comment by frankh** [comment]
I got this to work by passing initial data of {}. Feels like there should be a better way as you have to pass undefined as the auth param (or useAuth()) to pass the initial data in

`const { status, data: user, hasEmitted } = useUser(undefined, {initialData: {}});`

**Comment by amiregelz** [comment]
I also ran into this today. Thanks for updating with your workaround.
What's the meaning of `hasEmitted`?

**Comment by jhuleatt** [comment]
Thanks @mnlfischer for the repro! @jamesdaniels would you be able to look into this? `hasEmitted` is set here:

https://github.com/FirebaseExtended/reactfire/blob/9d96d92d212fbd616506848180e02e84d4866409/src/useObservable.ts#L82

**Comment by aalises** [comment]
Also ran into this issue. I need it specially so I can discern the `loading` state (auth not resolved) vs. the user is signed out. 

The workaround from @frankh solves this but it has the issue that does not set the `currentUser` correctly (I use it for setting it some auth token and it's `{}` with the workaround.
