### ISSUE TITLE
Indexed Collection Group Query produces infinite loop

### ISSUE THREAD

**Issue by JoFont** [FirebaseExtended/reactfire#351]
Hello, good afternoon.

I don't know if I'm missing something but subscribing to an indexed collectionGroup returns an infinite loop. It also doesn't trigger the usual Firestore error to index this query when one does not exist. I had to manually trigger a .get() using the firebase js API in order to get the url to create the index.

After successful indexing, I can use this query with the JS API but using with the ReactFire API sends the app in an infinite loop.

**React:**
0.0.0-experimental-27659559e
**Firebase:**
^8.2.5
**ReactFire:**
^3.0.0-rc.0

### Steps to reproduce

```js
  const tDate = moment().subtract(12, 'hours');
  const solarTelemetryRef = useFirestore().collectionGroup('telemetry').where('meta.createdAt', '>=', tDate.toDate());
  const { data: telemetryData } = useFirestoreCollectionData(solarTelemetryRef);
```

Please to let me know if this issue does not comply with the template and I'll make sure to provide more details.

Thank you very much for your help.
All the best,
Diogo Marques

**Comment by steurt** [comment]
I seem to have a similar problem. Using reactfire 3.0.0-rc.2 my app seems to get in an infinite loop of requests. Although in my case it is _not_ related to using the `collectionGroup`.

The UI of my app is in a continuous Suspended state, so I keep seeing my fallback component. When I inspect my network traffic, I see multiple requests with the same signature. One following the other. A request takes about ~1 min, is completed and is directly followed up with another same request that takes about ~1 min etcetera. This is continues endlessly.
The request signature:
https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2F{my-project}%2Fdatabases%2F(default)&gsessionid={gsessionid}&RID=rpc&SID={sid}&AID={aid}&TYPE=xmlhttp&zx={zx}&t=1

<img width="203" alt="Screen Shot 2021-07-15 at 17 16 50" src="https://user-images.githubusercontent.com/32896803/125812908-5ff99795-fa57-48fe-a48c-23835c203b80.png">
<img width="390" alt="Screen Shot 2021-07-15 at 17 11 36" src="https://user-images.githubusercontent.com/32896803/125812728-db7918b0-0751-41ef-8ada-a33d28b68428.png">

This is causing the app to keep suspending and is therefore blocking.

**Comment by steurt** [comment]
@JoFont I've had indefinite loop/suspending issues as well with v3.0.0-rc.*. They manifested at different times at different places in my app. I managed to get it working, not sure what the root cause is though. Maybe give my workaround a try and see if it solves your issues as well. For more details, see: https://github.com/FirebaseExtended/reactfire/issues/405#issuecomment-884860980.
