### ISSUE TITLE
AuthCheck loads Login page briefly on page refresh

### ISSUE THREAD

**Issue by MorenoMdz** [FirebaseExtended/reactfire#354]
https://user-images.githubusercontent.com/29472480/113232276-38fe0d00-9273-11eb-80c0-472cffeb3798.mov

### Version info

**React:** 16.13.1

**Firebase:** 8.3.1

**ReactFire:** 3.0.0-rc.0

We are moving our project from an old redux setup to Reactfire and maybe React Context if needed. I was able to move all the screens to reactfire hooks without major issues. The issue we are having is that on reload, the page is briefly displaying the login page (from AuthRoute) instead of showing either the Suspense spinner or just a blank screen.

React navigation works fine, the page doesn't refresh so React Router is working, if the page is refreshed/reloaded it resets the navigation history as wellÏ.

The doubt I have is, is it reloading the Auth check on every page reload so for an instant the auth object is empty?

Index.js:
```javascript
ReactDOM.render(
  <Sentry.ErrorBoundary fallback={'An error has occurred'}>
    <FirebaseAppProvider firebaseConfig={firebaseConfig}>
      <PanelsContextProvider>
        <App />
      </PanelsContextProvider>
    </FirebaseAppProvider>
  </Sentry.ErrorBoundary>,
  document.getElementById('root')
);
```

App.js:
```javascript
const App = () => (
  <Suspense fallback={<Spinner />}>
    <AuthCheck fallback={<AuthRoute />}>
      <Routes />
    </AuthCheck>
  </Suspense>
);

```

In the child component, it loads the user profile (renamed to keep it compatible with the old codebase that used to have the profile in the redux state), then it moves on the display the correct page depending on the profile data.

```javascript
function Routes() {
  const auth = useAuth();
  const { data: user } = useUser();
  const userDetailsRef = useFirestore()
    .collection('users')
    .doc(user.uid);

  let { data: profile } = useFirestoreDocData(userDetailsRef);

  console.log(profile, 'profile from App');

...
}
```

```javascript
const AuthRoute = () => (
  <BrowserRouter>
    <Switch>
      <Route exact path="/" component={Login} />
      <Route path="/signup/:orgId" component={Register} />
      <Route path="/signup" component={Register} />
      <Route path="/forgot" component={Login} />
      <Route render={() => <Redirect to="/" />} />
    </Switch>
  </BrowserRouter>
);
```

### Expected behavior

To not load a different component on page refresh.

### Actual behavior

User Login and stays logged in fine. The user logs out fine.

The page blinks to the Login screen then back to the current page.

**Comment by dlarroder** [comment]
You can try adding `suspense` on

```
<FirebaseAppProvider firebaseConfig={firebaseConfig} suspense>
      <PanelsContextProvider>
        <App />
      </PanelsContextProvider>
</FirebaseAppProvider>
```

**Comment by MorenoMdz** [comment]
> suspense

Thanks for the suggestion, with the suspense prop I get the suspense error:
`Error: App suspended while rendering, but no fallback UI was specified.`

What structure you are using in the index and app files?

**Comment by ItayElgazar** [comment]
@MorenoMdz Really? does this work for you? It works for me, but then I get "Loading" spinner everywhere for every action that requires firebase

**Comment by MorenoMdz** [comment]
> @MorenoMdz Really? does this work for you? It works for me, but then I get "Loading" spinner everywhere for every action that requires firebase

The spinner you get is from suspense or from fetching something? That structure is at my index.js

**Comment by ItayElgazar** [comment]
Yeah when I think about it it makes sense, it’s when I fetch something. But
you just have some global spinner when you fetch something then?

**Comment by MorenoMdz** [comment]
> Yeah when I think about it it makes sense, it’s when I fetch something. But you just have some global spinner when you fetch something then?

You can handle that in many different ways, having global stored isLoading state for example. In this application, we have a locally set loading state for each individual screen/page.
