### ISSUE TITLE
No Configuration Found

### ISSUE THREAD

**Issue by olawalejuwonm** [FirebaseExtended/reactfire#356]
### Version info

**React: latest**

**Firebase: latest**

**ReactFire: latest version**

**Other (e.g. Node, browser, operating system) (if applicable):**

### Test case
followed this https://github.com/FirebaseExtended/reactfire/blob/main/docs/use.md#combine-auth-firestore-and-cloud-storage-to-show-a-user-profile-card and still getting No Configuration Found Error

**Comment by jhuleatt** [comment]
@olawalejuwonm can you please include the full error message you're getting? It will make it easier for me to help.
