### ISSUE TITLE
Typo in auth example files?

### ISSUE THREAD

**Issue by w90** [FirebaseExtended/reactfire#365]
https://github.com/FirebaseExtended/reactfire/blob/b4f22bc0a84729245db87861d5190a0483b19348/example/withSuspense/Auth.tsx#L36

Hello, shouldn't that be ```useAuth()``` there?

**Comment by jhuleatt** [comment]
Hey @w90, good question! Even though it looks like it should have parens, `useAuth` uses a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) under the hood.

The reason for this is explained by @jamesdaniels  in https://github.com/FirebaseExtended/reactfire/pull/215#issue-376922716:

> Use my good friend `Proxy` to allow access to both the `serviceProps` and the initialized instance without double calling (e.g, `useAuth()()`)
