### ISSUE TITLE
'useSigninCheck' is not exported from 'reactfire'

### ISSUE THREAD

**Issue by alenakazarina** [FirebaseExtended/reactfire#375]
### Version info

**React:** 17.0.2

**Firebase:** 8.6.1

**ReactFire:** 3.0.0-rc.0

**Node:** 14.0.0

### Steps to reproduce

import {useSigninCheck} from 'reactfire';

### Expected behavior

useSigninCheck hook is imported

### Actual behavior

Attempted import error: 'useSigninCheck' is not exported from 'reactfire'.

**Comment by ColeSquared** [comment]
I am able to reproduce this. Any way to fix it?

**Comment by jhuleatt** [comment]
We haven't released a new RC that includes `useSigninCheck` - for now, please do `npm i reactfire@canary` to get a version that has `useSigninCheck`.

**Comment by ColeSquared** [comment]
Looks like the latest canary release is from 5 months ago and this also doesn't include `useSigninCheck`. Is there another way to install that does include this hook?
