### ISSUE TITLE
Support for modular firebase v9 SDK

### ISSUE THREAD

**Issue by devth** [FirebaseExtended/reactfire#388]
Feature request for supporting the [modular firebase v9](https://firebase.google.com/docs/web/learn-more#modular-version). Might be early but wanted to get an issue open to start tracking it.

[Docs on upgrading](https://firebase.google.com/docs/web/modular-upgrade) and some of the benefits you get.

**Comment by jhuleatt** [comment]
Hey @devth, thanks for the request. We're working on this in https://github.com/FirebaseExtended/reactfire/pull/369

**Comment by devth** [comment]
Awesome!

**Comment by jhuleatt** [comment]
I've started a new discussion (https://github.com/FirebaseExtended/reactfire/discussions/402) with more information about API changes that will go along with supporting v9. Please leave comments and questions in there!

**Comment by devth** [comment]
Thanks @jhuleatt and nice work! Looking forward to trying it out.
