### ISSUE TITLE
Failed to compile error when running dev react server

### ISSUE THREAD

**Issue by tigbeans** [FirebaseExtended/reactfire#404]
Hello,

I am receiving the following error when i run `npm run start` in my react project.

`
Failed to compile.
./node_modules/reactfire/node_modules/rxfire/database/index.esm.js
Attempted import error: '__spreadArray' is not exported from 'tslib'.
`

Here is my package.json dependencies
`
"dependencies": {
        "@testing-library/jest-dom": "^5.11.9",
        "@testing-library/react": "^11.2.5",
        "@testing-library/user-event": "^12.8.3",
        "file-loader": "^6.2.0",
        "firebase": "^8.7.1",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-icons": "^4.2.0",
        "react-router-dom": "^5.2.0",
        "react-scripts": "4.0.3",
        "reactfire": "^3.0.0-rc.2",
        "web-vitals": "^1.1.1"
    }
`

I have tried changing my reactfire version and also including a different version of rxfire in my package.json but nothing seems to help

### Version info

**React:**
17.0.2
**Firebase:**
8.7.1
**ReactFire:**
3.0.0-rc.2
**Other (e.g. Node, browser, operating system) (if applicable):**
Node: 14.17.3

### Expected behavior
Should compile successfully.

### Actual behavior
Compilation error when starting react server

Thanks!

**Comment by epodol** [comment]
What is the output of `npm ls reactfire`?

**Comment by epodol** [comment]
You can try deleting your node_modules folder and package-lock.json, then run `npm i`.

**Comment by tandalesc** [comment]
The same exact thing is happening to me. I've tried three different `node` versions and `reactfire` back to rc.0, and it's still failing to compile after deleting node_modules and running `npm i`. I'm not really sure what I'm doing wrong -- I basically followed the quickstart guide.

**Comment by epodol** [comment]
> The same exact thing is happening to me. I've tried three different `node` versions and `reactfire` back to rc.0, and it's still failing to compile after deleting node_modules and running `npm i`. I'm not really sure what I'm doing wrong -- I basically followed the quickstart guide.

Did you also delete the `package-lock.json` at the same time before doing `npm i`? That's what fixed it for me. (I'm running 3.0.0-rc.2 with Node 14)

**Comment by tandalesc** [comment]
@epodol Thanks! This actually fixed my problem :-)

**Comment by tigbeans** [comment]
@epodol the combination of deleting the node_modules folder and the package-lock.json seemed to do the trick. I had tried just deleting node_modules before but I guess the trick was deleting the package-lock.json too. Thanks :)

**Comment by epodol** [comment]
Glad to hear it @tandalesc and @tigbeans!
