### ISSUE TITLE
update CONTRIBUTING.md

### ISSUE THREAD

**Issue by jhuleatt** [FirebaseExtended/reactfire#439]
Add instructions to run:

```bash
yarn build
yarn test
yarn lint
yarn docs
```

before committing

**Comment by sujishpatel** [comment]
Might want to clarify that forked repos typically require the following to be added to the typedoc args `--gitRemote upstream` 

so in full it would be 
```typedoc --options typedoc.json --gitRemote upstream && markdown-toc -i docs/use.md```

**Comment by jhuleatt** [comment]
> Might want to clarify that forked repos typically require the following to be added to the typedoc args `--gitRemote upstream`
> 
> so in full it would be
> `typedoc --options typedoc.json --gitRemote upstream && markdown-toc -i docs/use.md`

Great point, I've [added a new `yarn docs:fork`](https://github.com/FirebaseExtended/reactfire/commit/8c7539aba27f5a4493ab024e92076e68e04ff3f0) command and added it to the [Before submitting a PR instructions](https://github.com/FirebaseExtended/reactfire/blob/main/.github/CONTRIBUTING.md#before-submitting-a-pr).
