### ISSUE TITLE
Cannot use any provider except FirebaseAppProvider

### ISSUE THREAD

**Issue by JurgenPalsma** [FirebaseExtended/reactfire#467]
Any provider import except FirebaseAppProvider gives me an error:
**Attempted import error: 'FunctionsProvider' is not exported from 'reactfire'.**

### Version info

"@firebase/functions": "^0.7.2",
  "@firebase/storage": "^0.8.2",
  "@salesforce/design-system-react": "^0.10.35",
  "@testing-library/jest-dom": "^5.11.4",
  "@testing-library/react": "^11.1.0",
  "@testing-library/user-event": "^12.1.10",
  "@types/react": "^17.0.15",
  "firebase": "^8.8.1",
  "react": "^17.0.2",
  "react-dom": "^17.0.2",
  "react-firebaseui": "^5.0.2",
  "react-router-dom": "^5.2.0",
  "react-scripts": "4.0.3",
  "reactfire": "^3.0.0-rc.3",
  "slate": "^0.60.17",
  "slate-history": "^0.60.17",
  "slate-hyperscript": "^0.62.0",
  "slate-react": "^0.60.17",
  "typescript": "^4.3.5",
  "web-vitals": "^1.0.1"

### Steps to reproduce
eg:`import {FunctionsProvider} from 'reactfire';`

### Expected behavior
Import success :)

### Actual behavior
Attempted import error: 'FunctionsProvider' is not exported from 'reactfire'.

**Comment by epodol** [comment]
FunctionsProvider is only needed/available for for firebase v9 (modular). You only have v8.8.1 (not modular) installed. So unless you update firebase to the latest version as well, you do not need to update reactfire.

If you update to the latest `firebase` version, you will need to update to the latest reactfire version. Try manually running `npm i reactfire@4.2.0`. 

Also, you are installing `@firebase/functions` and `@firebase/storage`. These both are included in `firebase` and should not be installed individually. From the firebase JS SDK GitHub repo:

> This package is not intended for direct usage, and should only be used via the officially supported firebase package.

**Comment by jhuleatt** [comment]
Thanks @epodol, that's correct. @JurgenPalsma, please take a look at the [upgrade guide](https://github.com/FirebaseExtended/reactfire/blob/main/docs/upgrade-guide.md) for more tips on moving to ReactFire v4.

**Comment by JurgenPalsma** [comment]
thank you all for the clarifications
