### ISSUE TITLE
React-firebaseui: Cannot read properties of undefined (reading 'initializeApp')

### ISSUE THREAD

**Issue by mankinchi** [FirebaseExtended/reactfire#478]
### Version info

**React:** 17.0.2

**Firebase:** 9.1.3

**ReactFire:** 4.2.0

**react-firebaseui**: 5.0.2

### Test case
Main component
![image](https://user-images.githubusercontent.com/8164063/137491720-13401da5-e640-40fd-9b59-3536e3213cbd.png)

Layout component
![image](https://user-images.githubusercontent.com/8164063/137491743-e3716a5e-463f-4691-81af-83b0aa4af2e5.png)

You can see that the provider is set up correctly

Component
![image](https://user-images.githubusercontent.com/8164063/137491804-808ae2ac-dfb7-4643-8d19-2881ce916c00.png)

### Expected behavior

FirebaseUI to work correctly.

Side question: How can I grab the provider ID for firebase auth? Should I grab it straight from `firebase/auth` instead of using `useAuth` hook?

### Actual behavior

Error
![image](https://user-images.githubusercontent.com/8164063/137491931-ed389cb4-b5bc-43af-b814-56f83922d952.png)

**Comment by jhuleatt** [comment]
Hi @mankinchi and @nbangba, v6 of react-firebaseui only works with the compat imports of Firebase v9, described here: https://github.com/firebase/firebaseui-web-react/pull/158#issuecomment-964269348

There's also a discussion about this here: https://github.com/FirebaseExtended/reactfire/discussions/474. I'll try to post an example of how to use FirebaseUI react-firebaseui v6 alongside ReactFire v4 soon.

**Comment by Imprasna** [comment]
![Screenshot 2021-11-26 104045](https://user-images.githubusercontent.com/31104095/143530159-f0651a6a-cffc-4323-aa6e-d46e32e7bc09.png)
 I want to fix this, but I don't know what am I supposed to do. Can anyone help me fix this issue please.

**Comment by jhuleatt** [comment]
I posted a workaround here: https://github.com/FirebaseExtended/reactfire/discussions/474#discussioncomment-1737817

Please give it a try and comment in that discussion if it isn't working :)
