### ISSUE TITLE
Add an option to only enable the query when `enabled` option is set

### ISSUE THREAD

**Issue by Manokii** [FirebaseExtended/reactfire#512]
### Description
Add an option to only do the queries if `enabled` is set and has truthy value. This behavior is similar to `react-query`'s [`QueryOptions.enabled`](https://react-query.tanstack.com/guides/migrating-to-react-query-3#if-set-the-queryoptionsenabled-option-must-be-a-boolean-truefalse=)

### Why?
Sometimes a query might depend on another query

**Comment by bookchris** [comment]
react-firebase-hooks, useSWR, etc handles this by accepting a null query, which is another option.
